on:
  workflow_dispatch:
  schedule:
    - cron: '45 4 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay-3es/ha1dy-2ib3et4o@cron
        with:
          token: ${{ secrets.token }}
